# archivo_config.yml

site_name: "Abstractions"
baseurl: "/"
language: "es"
author:
  name: "Carlos Alberto Villarreal Noyola"
  # email: "tu@correo.example"

# Opciones de build
# markdown: kramdown
permalink: /:title.html

# Variables personalizadas
show_author: false
show_date: false

# Configuraci√≥n de colecciones
collections:
  pages:
    output: true
    permalink: /:name.html
  articulos:
    output: true

# Google Analytics
google_analytics: G-DX9PGTB7JC